# Generated by Django 5.1.7 on 2025-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_template_template_dir_alter_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='ci_template',
            field=models.TextField(blank=True, help_text='Шаблон ci.yml для GitHub Actions'),
        ),
    ]
